### ISSUE TITLE
Interstitial and rewarded ads not working correctly on iOS 13

### ISSUE THREAD

**Issue by jm1175** [Lerg/extension-admob#13]
When testing the sample project on iOS 13 the interstitial and rewarded ads are not working correctly. They load fine but when you go to show an ad they don't appear. It also stops you from being able to tap any buttons even though there's no ad on the screen.

You can get the ad to appear by returning to the home screen and then reopening the app. But tapping the 'x' button won't close the ad immediately. You have to return to the home screen again and reopen the app, after that the ad will be closed.

**Comment by Lerg** [comment]
Fixed, thanks for reporting!

**Comment by linpochih** [comment]
When testing the sample project on iOS devices, the app crashes when launching.

**Comment by linpochih** [comment]
> Fixed, thanks for reporting!

When testing the sample project on iOS devices, the app crashes when launching.

**Comment by Lerg** [comment]
Sorry, we have to wait for a fix in the engine. https://forum.defold.com/t/defold-1-2-164-delayed/63742
