### ISSUE TITLE
iOS simulator build fails

### ISSUE THREAD

**Issue by jm1175** [Lerg/extension-admob#14]
I'm getting the following errors when building for iOS simulator using the sample project:

ld: warning: ignoring file /tmp/job13253772705943058690/upload/admob/lib/ios/libextension.admob.a, missing required architecture x86_64 in file /tmp/job13253772705943058690/upload/admob/lib/ios/libextension.admob.a (2 slices)

Undefined symbols for architecture x86_64:
  "__Z28Extension_admob_enable_debugP9lua_State", referenced from:
      __ZL13lua_functions in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z30Extension_admob_app_deactivateP9lua_State", referenced from:
      __Z24Extension_admob_on_eventPN11dmExtension6ParamsEPKNS_5EventE in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z28Extension_admob_app_activateP9lua_State", referenced from:
      __Z24Extension_admob_on_eventPN11dmExtension6ParamsEPKNS_5EventE in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z24Extension_admob_finalizeP9lua_State", referenced from:
      __Z24Extension_admob_FinalizePN11dmExtension6ParamsE in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z27Extension_admob_hide_bannerP9lua_State", referenced from:
      __ZL13lua_functions in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z22Extension_admob_updateP9lua_State", referenced from:
      __Z22Extension_admob_UpdatePN11dmExtension6ParamsE in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z26Extension_admob_initializeP9lua_State", referenced from:
      __Z26Extension_admob_InitializePN11dmExtension6ParamsE in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z20Extension_admob_showP9lua_State", referenced from:
      __ZL13lua_functions in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z20Extension_admob_initP9lua_State", referenced from:
      __ZL13lua_functions in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z25Extension_admob_is_loadedP9lua_State", referenced from:
      __ZL13lua_functions in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)
  "__Z20Extension_admob_loadP9lua_State", referenced from:
      __ZL13lua_functions in lib29a45390-de6b-4b84-95f1-77356404ae56.a(extension.cpp_3.o)

ld: symbol(s) not found for architecture x86_64

clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Lerg** [comment]
Should be working in the new version.
