### ISSUE TITLE
add 'arm64-android' to game.appmanifest

### ISSUE THREAD

**Issue by Dragosha** [Lerg/extension-admob#2]
`platforms:
    armv7-android:
        context:
            excludeJars: ["(.*)/google-play-services.jar", "(.*)/android-support-v4.jar"]
    arm64-android:
        context:
            excludeJars: ["(.*)/google-play-services.jar", "(.*)/android-support-v4.jar"]`

there is a build error when create 64-bit Android version:
![2019-06-11_17-31-11](https://user-images.githubusercontent.com/842807/59272628-d8ea4100-8c6f-11e9-98c8-7da8b307bba2.png)

**Comment by Lerg** [comment]
Fixed, thanks.
