### ISSUE TITLE
Hi, i can't find ext.appmanifest

### ISSUE THREAD

**Issue by Sun-FreePort** [Lerg/extension-admob#3]
In README.md, i see " native_extension to /admob/ext.appmanifest.", where has this file?

**Comment by Sun-FreePort** [comment]
Oh, i find it! I see you commit again and again in short time, Why you can't create dev branch?

**Comment by Lerg** [comment]
Sorry, it's a bit chaotic, but not chaotic enough for a separate dev branch.
