### ISSUE TITLE
Attribute "fontProviderAuthority" has already been defined

### ISSUE THREAD

**Issue by Sun-FreePort** [Lerg/extension-admob#4]
I find "Build Errors" when bundle Android app:

```log
Failed building Android resources to R.java: C:\Users\ADMINI~1\AppData\Local\Temp\bob_bundle_tmp6080746162126291939\res\values\values.xml:50: error: Attribute "fontProviderAuthority" has already been defined

C:\Users\ADMINI~1\AppData\Local\Temp\bob_bundle_tmp6080746162126291939\res\values\values.xml:53: error: Attribute "fontProviderPackage" has already been defined

C:\Users\ADMINI~1\AppData\Local\Temp\bob_bundle_tmp6080746162126291939\res\values\values.xml:56: error: Attribute "fontProviderQuery" has already been defined

C:\Users\ADMINI~1\AppData\Local\Temp\bob_bundle_tmp6080746162126291939\res\values\values.xml:62: error: Attribute "fontProviderCerts" has already been defined
```

I use myself project / this repo master branch try it, the error info has again.

**Comment by Lerg** [comment]
Doesn’t work on windows yet. You can try mac or linux.

**Comment by Lerg** [comment]
Updated the extension, please try again.

**Comment by rsolovjov** [comment]
If I clone that project, open it and bundle for Android getting an error:

Line 7: Attribute "fontProviderAuthority" has already been defined
Line 7: Attribute "fontProviderPackage" has already been defined
Line 7: Attribute "fontProviderQuery" has already been defined
Line 7: Attribute "fontProviderCerts" has already been defined
Line 7: Attribute "fontProviderFetchStrategy" has already been defined
...

For iOS everything is working correctly
Please, help 

MacOS Defold v1.2.165
