### ISSUE TITLE
Failed merging manifests: java.lang.RuntimeException: Failed to merge manifests: com.android.manifmerger.MergingReport@5de7b7ba

### ISSUE THREAD

**Issue by Ceydigitaluditha** [Lerg/extension-admob#6]
This error occurs when i am trying to build an android app using defold

Earlier discussion

https://forum.defold.com/t/failed-merging-manifests-java-lang-runtimeexception-failed-to-merge-manifests-com-android-manifmerger-mergingreport-5de7b7ba/56005

**Comment by Lerg** [comment]
Updated the extension, please try again.
