### ISSUE TITLE
Bundling android application results in error with manifest

### ISSUE THREAD

**Issue by lrxit** [Lerg/extension-admob#7]
Bundling android application results in error with manifest:

![bundleerror](https://user-images.githubusercontent.com/49574732/60301568-056db080-9932-11e9-9796-f7b577eeffc4.PNG)

It works commenting out InAppPurchaseActivity

![aaa](https://user-images.githubusercontent.com/49574732/60301762-7ca34480-9932-11e9-8de5-23b4b1fc9d15.PNG)

Easy but this prevent to use extension as a dependency.

**Comment by Lerg** [comment]
Updated the extension, please try again.

**Comment by lrxit** [comment]
I've tried, but problem persists:

![proplem_persist](https://user-images.githubusercontent.com/49574732/60624159-d305fc80-9de4-11e9-8d76-fc288a632147.png)

Maybe I'm doing something wrong.

**Comment by Lerg** [comment]
Turns out this is a bug in Windows version of Defold. Bundling works on macOS or Linux. They are working on a fix for Windows now.

**Comment by lrxit** [comment]
Thanks for the clarification!

**Comment by lrxit** [comment]
Defold released version 1.2.158, now works well.

**Comment by Lerg** [comment]
Thank you for reporting!
