### ISSUE TITLE
Warning: [options] bootstrap class path not set in conjunction with -source 1.6

### ISSUE THREAD

**Issue by Ceydigitaluditha** [Lerg/extension-admob#8]
when i am trying to build an Android version of my game system popup this error message, 

![image](https://user-images.githubusercontent.com/36755708/60508797-111df600-9ce9-11e9-87ec-1e08b3afcb2a.png)

![image](https://user-images.githubusercontent.com/36755708/60508809-1713d700-9ce9-11e9-9c55-11b80e138587.png)

Issue related to : https://forum.defold.com/t/warning-options-bootstrap-class-path-not-set-in-conjunction-with-source-1-6/56492

**Comment by Lerg** [comment]
Updated the extension, please try again.
